// This file is auto-generated by scripts/compile-samples.tsx — do not edit manually.
// To add or update samples, open a PR to: https://github.com/documentdb/documentdb-samples-gallery
import { Sample } from '../types/Sample';

export const samples: Sample[] = [
  {
    id: 'book-finder-js',
    title: 'BookFinder: AI-Powered Semantic Book Discovery',
    description: 'A Node.js/Express app that uses OpenAI embeddings and DocumentDB vector search to let users discover books through natural language queries like \'dystopian future with rebellion\'.',
    language: 'Node.js',
    industry: 'AI/ML',
    difficulty: 'Intermediate',
    tags: ['Vector Search', 'OpenAI', 'Embeddings', 'Express', 'Semantic Search'],
    githubUrl: 'https://github.com/documentdb/documentdb-samples-gallery/tree/main/book-finder-js',
  }
];
