#!/usr/bin/env tsx

import fs from 'fs';
import path from 'path';
import { spawnSync } from 'child_process';
import React from 'react';
import { render, Box, Text } from 'ink';
import yaml from 'js-yaml';

/**
 * Configuration for the samples registry
 */
interface SamplesConfig {
  readonly repository: string;
  readonly branch: string;
  readonly registryFile: string;
}

/**
 * A single sample entry as defined in registry.yml
 */
interface RegistrySample {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly language: string;
  readonly industry: string;
  readonly difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  readonly tags: ReadonlyArray<string>;
  readonly githubUrl: string;
}

interface Registry {
  readonly samples: ReadonlyArray<RegistrySample>;
}

interface CompileResult {
  readonly success: boolean;
  readonly count?: number;
  readonly skipped?: boolean;
  readonly message?: string;
}

const TEMP_DIR = path.join(process.cwd(), '_tmp_samples');
const OUTPUT_FILE = path.join(process.cwd(), 'app', 'data', 'samples.ts');

/**
 * Cleans a directory by removing it if it exists
 */
function cleanDirectory(dirPath: string): void {
  if (fs.existsSync(dirPath)) {
    fs.rmSync(dirPath, { recursive: true, force: true });
  }
}

/**
 * Generates the samples.ts file content from a list of samples
 */
function generateSamplesFile(samples: ReadonlyArray<RegistrySample>): string {
  const entries = samples.map((s) => {
    const tags = s.tags.map((t) => `'${t}'`).join(', ');
    return `  {
    id: '${s.id}',
    title: '${s.title.replace(/'/g, "\\'")}',
    description: '${s.description.replace(/'/g, "\\'")}',
    language: '${s.language}',
    industry: '${s.industry}',
    difficulty: '${s.difficulty}',
    tags: [${tags}],
    githubUrl: '${s.githubUrl}',
  }`;
  });

  return `// This file is auto-generated by scripts/compile-samples.tsx — do not edit manually.
// To add or update samples, open a PR to: https://github.com/documentdb/documentdb-samples-gallery
import { Sample } from '../types/Sample';

export const samples: Sample[] = [
${entries.join(',\n')}
];
`;
}

/**
 * Clones the registry repo and generates samples.ts from registry.yml
 */
async function compileSamples(config: SamplesConfig): Promise<CompileResult> {
  try {
    cleanDirectory(TEMP_DIR);
    fs.mkdirSync(TEMP_DIR, { recursive: true });

    const repoName = config.repository.split('/').pop() ?? 'samples-registry';
    const cloneDir = path.join(TEMP_DIR, repoName);

    spawnSync(
      'git',
      ['clone', '--depth', '1', '--branch', config.branch, config.repository, cloneDir],
      { stdio: 'pipe' }
    );

    const registryPath = path.join(cloneDir, config.registryFile);
    if (!fs.existsSync(registryPath)) {
      throw new Error(`Registry file not found: ${config.registryFile}`);
    }

    const registry = yaml.load(fs.readFileSync(registryPath, 'utf8')) as Registry;

    if (!registry?.samples || !Array.isArray(registry.samples)) {
      throw new Error('registry.yml must contain a top-level "samples" array');
    }

    const generated = generateSamplesFile(registry.samples);
    fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
    fs.writeFileSync(OUTPUT_FILE, generated, 'utf8');

    cleanDirectory(TEMP_DIR);

    return { success: true, count: registry.samples.length };
  } catch (err: unknown) {
    cleanDirectory(TEMP_DIR);

    // If the registry repo doesn't exist yet, skip gracefully rather than failing the build
    const msg = err instanceof Error ? err.message : String(err);
    if (msg.includes('repository') || msg.includes('not found') || msg.includes('clone')) {
      return { success: true, skipped: true, message: msg };
    }

    return { success: false, message: msg };
  }
}

/**
 * Main Console component for Ink rendering
 */
const Console: React.FC = () => {
  const [status, setStatus] = React.useState<'loading' | 'compiling' | 'success' | 'skipped' | 'error'>('loading');
  const [errorMessage, setErrorMessage] = React.useState<string>('');
  const [sampleCount, setSampleCount] = React.useState<number>(0);
  const [config, setConfig] = React.useState<SamplesConfig | null>(null);

  React.useEffect(() => {
    const run = async () => {
      try {
        const configPath = path.join(process.cwd(), 'samples.config.json');
        if (!fs.existsSync(configPath)) {
          throw new Error('samples.config.json not found');
        }

        const loadedConfig = JSON.parse(fs.readFileSync(configPath, 'utf8')) as SamplesConfig;
        setConfig(loadedConfig);
        setStatus('compiling');

        const result = await compileSamples(loadedConfig);

        if (!result.success) {
          setStatus('error');
          setErrorMessage(result.message ?? 'Unknown error');
        } else if (result.skipped) {
          setStatus('skipped');
          setErrorMessage(result.message ?? '');
        } else {
          setStatus('success');
          setSampleCount(result.count ?? 0);
        }

        setTimeout(() => {
          process.exit(result.success ? 0 : 1);
        }, 100);
      } catch (err: unknown) {
        setStatus('error');
        setErrorMessage(err instanceof Error ? err.message : 'Unknown error');
        setTimeout(() => process.exit(1), 100);
      }
    };

    run();
  }, []);

  return (
    <Box flexDirection="column" padding={1}>
      <Box marginBottom={1}>
        <Text bold color="cyan">🗂️  Compiling Samples Registry</Text>
      </Box>

      {status === 'loading' && (
        <Box>
          <Text color="cyan">Loading configuration...</Text>
        </Box>
      )}

      {status === 'compiling' && config && (
        <Box flexDirection="column">
          <Text color="cyan">Cloning {config.repository}...</Text>
        </Box>
      )}

      {status === 'success' && (
        <Box flexDirection="column">
          <Text bold color="green">✅ Generated samples.ts with {sampleCount} sample{sampleCount !== 1 ? 's' : ''}!</Text>
          <Text dimColor>→ app/data/samples.ts</Text>
        </Box>
      )}

      {status === 'skipped' && (
        <Box flexDirection="column">
          <Text bold color="yellow">⚠️  Samples registry not available — using existing samples.ts</Text>
          <Text dimColor>{errorMessage}</Text>
        </Box>
      )}

      {status === 'error' && (
        <Box flexDirection="column">
          <Box marginBottom={1}>
            <Text color="red" bold>❌ Error compiling samples registry:</Text>
          </Box>
          <Box paddingLeft={2}>
            <Text color="red">{errorMessage}</Text>
          </Box>
        </Box>
      )}
    </Box>
  );
};

render(<Console />);
